version: "3.8"
services:
  service1:
    image: abroomfield/server
    build: ./server
    environment: 
      DATABASE_URI: ${DATABASE_URI}
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
    - "service4"
  service2:
    image: abroomfield/class-api
    build: ./class-api
  service3:
    image: abroomfield/race-api
    build: ./race-api
    depends_on:
    - "service2"
  service4:
    image: abroomfield/stat-api
    build: ./stat-api
    depends_on:
    - "service3"