version: "3.8"
services:
  server:
    image: abroomfield/server
    build: ./server
    environment: 
      DATABASE_URI: ${DATABASE_URI}
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 5
    depends_on:
    - "stat_api"
  class_api:
    image: abroomfield/class-api
    build: ./class-api
    deploy:
      replicas: 5
  race_api:
    image: abroomfield/race-api
    build: ./race-api
    deploy:
      replicas: 5
    depends_on:
    - "class_api"
  stat_api:
    image: abroomfield/stat-api
    build: ./stat-api
    deploy:
      replicas: 5
    depends_on:
    - "race_api"