---
# tasks file for swarm-manager
- name: "Init a new swarm with default parameters"
  docker_swarm:
    state: present

- name: "Get info on Docker Swarm"
  docker_swarm_info:
  ignore_errors: yes
  register: swarm_info

- name: "Show info"
  debug:
    msg: "{{ swarm_info }}"