---
# tasks file for install-docker
- name: "Install Dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip
    update_cache: true

- name: "Get docker key"
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add docker repo"
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: "Install Docker"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: "Add user to docker group"
  ansible.builtin.user:
    name: andrew
    groups: docker
    append: yes

- name: "Install docker with pip"
  pip:
    name: docker
    executable: pip3

